### ISSUE TITLE
Issue about key config google maps

### ISSUE THREAD

**Issue by tjmelo** [tjmelo/tmx-jupter#12]
Proposal
---
To mention about include .env with key of google maps for show correctly map on app.

**Comment by tm-wd** [comment]
Fix bug code Google Maps. 
The map is not showing correctly because issue of the code register map. Please take a look at the print below for blank space.

![tmx-zipcode-netlify-app](https://github.com/tjmelo/tmx-jupter/assets/101524755/cc3f8776-e293-482d-ac5e-6d28ca6db461)

**Comment by tjmelo** [comment]
The issue was resolved by creating an environment variable on the server deployment.
🥇

**Comment by tjmelo** [comment]
The issue was resolved by creating an environment variable on the server deployment.
🥇
